kasutajad_db

diff --git a/praks3/kasutajad_db b/praks3/kasutajad_db
--- a/praks3/kasutajad_db
+++ b/praks3/kasutajad_db
@@ -1,28 +1,18 @@
 #!/bin/bash
-kasutaja=$1
-parool=$(pwgen 8 1)
-lahtekaust="/home/$kasutaja/"
-#otsime kaustas .my.cnf faili
-for filename in $(ls -la $lahtekaust); do
-	if [ -f $filename -eq '.my.cnf' ];
-	then
-	echo "Andmebaas on olemas"
+for kasutaja in $(ls /home)
+do
+	ls -la /home/$kasutaja | grep '\.my\.cnf' > /dev/null
+	kontroll=$?
+	if [ $kontroll -eq 1 ]; then
+		user=$(stat -c '%U' /home/$kasutaja)
+		grupp=$(stat -c '%G' /home/$kasutaja)
+		if [ "$user" = "root" ] && [ "$grupp" = "root" ]; then
+			continue
+		else
+			echo "fail puudub $kasutaja kasutajal"
+			sh lisa_db $kasutaja
+		fi
 	else
-	if [ -f $filename -ne '.my.sql' ]; then
-# mysql käsud
-mysql -e "CREATE DATABASE ${kasutaja};"
-mysql -e "CREATE USER ${kasutaja}@localhost IDENTIFIED BY '${parool}';"
-mysql -e "GRANT ALL PRIVILEGES ON ${kasutaja}.* TO '${kasutaja}'@'localhost';"
-mysql -e "FLUSH PRIVILEGES;"
-
-#konfi loomine
-touch /home/$kasutaja/.my.cnf
-echo "[client]
-user = $kasutaja
-password = $parool
-host = localhost" > /home/$kasutaja/.my.cnf
-chmod 0600 /home/$kasutaja/.my.cnf
-chown -R $kasutaja:user /home/$kasutaja/
+		echo "$kasutaja on korras"
 	fi
-fi
 done
